# Generated by Django 3.2.3 on 2021-07-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myeblog', '0004_auto_20210724_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='insta_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_url',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
